apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: humanhash
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    api_addr = "http://vault:8200"
    ui = true
