FROM ubuntu:18.04
RUN apt-get update && apt-get install -y wget libc6 libgcc1 libstdc++6 libtinfo5 libncurses5
RUN wget https://bitcoin.org/bin/bitcoin-core-0.16.3/bitcoin-0.16.3-x86_64-linux-gnu.tar.gz
RUN tar -xzf bitcoin-0.16.3-x86_64-linux-gnu.tar.gz
RUN mv bitcoin-0.16.3/bin/bitcoind /usr/local/bin/
RUN rm -rf bitcoin-0.16.3*
CMD ["bitcoind"]
